name: relatasapp
description: Relatas mobile app.
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  intl: ^0.17.0
  email_validator: ^2.0.1
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  infinite_scroll_pagination: ^3.1.0
  scroll_snap_list: ^0.8.2
  rxdart: ^0.27.2
  reactive_forms: ^10.6.2
  flutter_typeahead: ^3.2.1
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3


flutter:
  uses-material-design: true
  assets:
    - lib/images/logoname.png

flutter_icons:
  image_path: "lib/images/logo.jpg"
  android: true
  ios: true

flutter_native_splash:
  background_image: "lib/images/splash.png"
